services:
  cli:
    build:
      context: .
      target: cli
      dockerfile: Dockerfile
    image: "laravel-trustup-io-media-php-local"
    volumes:
      - ./:/opt/apps/app
    env_file:
      - .env
  bun:
    build:
      context: .
      target: bun
      dockerfile: Dockerfile
    image: "laravel-trustup-io-media-bun-local"
    volumes:
      - ./:/opt/apps/app